- click_helpers.py
- constants.py
- generic_helpers.py
- screen_helpers.py
- system_helpers.py
- tft.py
This is an initial pass at splitting the monolithic single-file code into modules, breaking out into related categories
This also highlights a recent change I pushed directly to `master` which updates the post-game logic to bring the League client to the forefront, which fixes situations that the client would get stuck on the `Find Match` or `Play Again` screen even though it appeared to be the 'forefront' window and be 'active'. Just tested it out for the last 18 hours and it's worked even better than expected, requiring 0 human intervention this morning until now after running since last night
> Initial Split Into Modules, Bump PR Relating To Window Restore Fixes

- requirements.txt
Adds the missing `keyboard` requirement
Fixes https://github.com/Kyrluckechuck/tft-bot/issues/18
> Add `keyboard` Requirement

- .github/workflows/ci.yml
- README.md
- Update "official" Python version from `3.8.3` to `3.10`
- Add CI pipeline so that any `main` push will get built, but only `main` merges will get official releases
- Assuming these builds are successful and work, they can be manually promoted from PreRelease, but this takes care of creating them (and makes it much easier for new users to test)
TODO (in future PR):
- Update `README.md` to mention this as the preferred way for users to use this
- Add ability to load from config file of some sort so that verbose can be enabled without running via CLI
> Build `main` On `push`, Creating PreRelease Releases

- .gitignore
- README.md
- tft.py
Load settings from `bot_settings.ini`, though if specified on CLI those will take highest precedence.
This is mainly to allow me to not have to always run with `-v` for verbose, since generally unchanging when I'm developing. This config structure also makes it "easier" for using the executable as you can "set it and forget it".
Pretty basic for now, may be more useful in the future.
> Load From Settings File, With CLI Taking Precedence

- .github/workflows/ci.yml
Pre-releases & tags were being generated for every push to `main`, but I'd prefer to be able to batch them a little cleaner.
Manual tag creation isn't an issue, so let's go that route first.
> Update Release Process To Not Generate Tags

- README.md
- system_helpers.py
- tft.py
This adds support for manual League install directory specification (via config), and associated README updates.
Theoretically this should enable Garena support (if they specify the install folder via config file using syntax in README)
This fixes https://github.com/Kyrluckechuck/TFT-Bot/issues/37
> Add Support For Manual League Install Directory Specification Via Config

- system_helpers.py
Pass all paths into `pathlib` to convert to Windows-safe path (which will result in consistent slash formatting)
Fixes https://github.com/Kyrluckechuck/TFT-Bot/issues/43
> Convert All Paths To Expected Format (Sanitize Slashes)

- tft.py
Quality of life improvement to allow you to disable resuming next game in the time between the game finishing and the next queue having started.
> Interrupt Existing/Started Lobby Loop

- tft.py
Fix scenarios where League client could have no UI after the TFT game ends and the bot would be stuck indefinitely
> Account For No Client UI Bug

- .github/workflows/ci.yml
- .github/workflows/linting.yml
Right now the two main CI steps only trigger on `push`, but the `push` event does not happen if it's an external pull request.
A followup should be made at some point to actually enable the linting, since right now all it does is confirm the dependencies install correctly.
> Update Actions Workflow To Work For Pull Requests

- constants.py
- tft.py
Kill the ~Rito~ Riot client when starting/restarting the league client.
This will account for a scenario where the RiotClientServices process has decided it lives in the background and interferes with launching League.
Fixes https://github.com/Kyrluckechuck/TFT-Bot/issues/102
> Kill Riot Client When Starting League

- .github/workflows/ci.yml
- .github/workflows/linting.yml
- README.md
- requirements.txt
Updates the project to use Python 3.11, and removes the 3.10 linting test since there's no reason to still run that.
In the release notes, ensure to mention that while this will likely continue to work on 3.10 installs, all bugs and issues on that version will be considered unsupported.
This also adds the Windows-only marker for `pywin32` so that if you're using WSL on Windows you are still able to do a `pip install` to get the pre-commit package without it fighting you that `pywin32` is not available on Linux.
Addresses #109
> Update To Python 3.11

- tft.py
Implements a better way to fall back on regarding ending lost games by asking the program to exit through `taskkill` gracefully.
I've been considering making this the standard way of exiting. However, there is a delay between us reaching 0 HP and the game showing Exit buttons to wait for all combats to finish, so I decided not to.
Out-of-scope commit fixing an issue that's not worth a separate PR, fixes #119 
Addresses #118 (Not saying it's fixed before the user confirms it this time.)
> Add graceful game end logic

- tft.py
I forgot to remove a line to parse which process we're terminating when reverting to using a list as arguments for taskkill.
> Fix process kill

- installer.py
- tft.py
This PR addresses "Version detection" of #124. It makes more sense to keep the config versioning separate from the project versioning, so we do not update the config for updates that do not edit it.
Implements a version update notifier by sending an API request to this repository's latest release, comparing the tag with the string in the `VERSION` file. The comparison ignores everything in the semantic version after the `patch` segment (position 3).
When a new version is detected, the user will be notified on start-up through a pop-up detailing their and the repository's version. They may download it (the button opens the release page in their default browser) or ignore it.
I decided to implement this first since it seems that we have had quite a few releases recently :)
Usually, you …
> Add update notifier

- tft_bot/config.py
Creates the config/log output directory if it does not already exist
Fixes https://github.com/Kyrluckechuck/TFT-Bot/issues/127
> Create Config/Log Output Directory If Not Existing

- tft.py
- tft_bot/league_api/league_api_integration.py
This PR adds changes that catch some new errors that may occur since we switched to HTTP requests.
We now also catch KeyboardInterrupt to correctly display that we know we should exit instead of printing a random stack trace.
In addition, a fix has been added to check if our session has expired.
Fixes #133 
Fixes #134
> Catch more errors

- README.md
- tft.py
- tft_bot/config.py
- tft_bot/league_api/league_api_integration.py
- tft_bot/resources/config.yaml
Addresses one of the tasks in #124. Adds a map to the config with pre-defined timeouts. Leverages enum, so it's as little effort as possible on our side to add more timeout options in the future.
Fixes an issue where the bot got stuck if the session expires while being in-game.
Fixes an issue where we got an error if the match history returns None.
Now prints the timer if CTRL+C was pressed. Additionally limits the timer from being printed too many times.
I've also tried adding a fitting gif to follow your fancy PRs :D
> Add configurable timeouts

- tft_bot/helpers/system_helpers.py
Instead of prepending the current directory to the asset path, change the local application context to ensure it's using the applications directory context. This will help avoid weird ASCII vs Unicode issues specifically relating to the directory/path the application is being executed in (or the temp files are run from).
Fixes #129
I haven't tested this too deeply, but I have run the bot from source the last few days without issue.
> Switch Directory To Avoid Loading Full Paths For Assets

- README.md
- requirements.txt
- tft.py
- tft_bot/config.py
- tft_bot/economy/base.py
- tft_bot/economy/default.py
- tft_bot/economy/ocr_standard.py
- tft_bot/helpers/screen_helpers.py
- tft_bot/helpers/system_helpers.py
- tft_bot/resources/config.yaml
Refactors part of the main game loop into a new economy module called `default`, which will remain the default.
Adds a new economy module called `ocr_standard`, which uses OCR to detect how much gold we have and makes a decision based on it. It behaves almost exactly as default: it equally buys units, levels, and rolls the shop. The key difference is that it saves and stays around 50 gold.
I concluded that it is not good to ship pre-built binaries/wheels for ML models and documented in the README how to enable the new option, emphasizing it as an optional nice-to-have.
In case you're wondering about the dependency injection, pylint started detecting circular imports that weren't an issue and have been there before. The DI approach I took should be acceptable to fix it, I am open to …
> Add economic decisions backed by OCR

- tft.py
- tft_bot/helpers/system_helpers.py
Now always waits for an internet connection before starting the league client. The reason is that the Rito Client also checks for internet, and we did not have a check yet.
It also replaces some of the sys.exit calls with restart_league_client.
Fixes #147, I hope?
I'd love to get `check_if_client_error` integrated with LCU (which should effectively take care of any error the client could throw at us), but I rarely run into client errors while physically present. I checked the LCU explorer but couldn't find anything at first glance (even though I did find that we can create arbitrary boxes and notification pop-ups ourselves, lol), so if you run into a box yourself, I'd love for you to see if you can find something with the explorer :)
> Increase Client Error Handling Robustness

- installer.py
- tft.py
- tft_bot/helpers/screen_helpers.py
Adds a new screen helper method to get the approximate position of units on the board.
This is the first step in adding item logic. I haven't done more yet since I think it's better to PR this step-by-step.
I've done my best to show what the steps in OpenCV are doing:
In text-form:
1. Take a screenshot and convert the colors to an HSV range we can work with
2. Remove everything except certain green colors in the image (as a mask, that's why black&white)
3. Remove noise (small / random pixels)
4. Expand the left-over pixels
5. Blur the pixels so they get merged together
6. Group them as a rectangle
Based on those groups, the actual Y position on the board is calculated.
This is what the debug line should look like:
```
2023-05-27 02:36:22.160 | DEBUG    | __main__:main_game_loop:540 - …
```
> Estimate Unit Positions

- tft.py
- tft_bot/config.py
- tft_bot/constants.py
- tft_bot/helpers/system_helpers.py
- tft_bot/league_api/league_api_integration.py
- tft_bot/resources/config.yaml
Some long overdue updates since I haven't been using this for the last while, but have been for the last couple event passes.
- Updates the league app to launch via the `RiotClientServices.exe` launch call, the same way that the `League of Legends` shortcut would launch the game. This should fix most scenarios which would open either the Riot Client or other sub-clients and launches League directly.
- As part of this, we now try to parse out the Riot Client install location as well. Since there is no obvious registry entries for it (at least that I could find), I opted to parse it out of the League client uninstaller path.
- If this eventually stops working and another path / reliable detection method isn't added, we may just swap to hard-coding this and making it so the bot user has to …
> Update League Client To Use ClientServices Launcher, API Tweaks

- tft.py
- tft_bot/league_api/league_api_integration.py
If the league client closed in various circumstances, the client would infintitely try to re-create the tft lobby but fail since the client was not actually connected anymore.
This updates that logic to parse the session status message in order to detect if the client is no longer communicating properly
> Restart League Client If Disconnected And/or Sending Confusing Messages

- tft.py
- tft_bot/config.py
- tft_bot/constants.py
- tft_bot/helpers/system_helpers.py
- tft_bot/resources/config.yaml
[Deceive](https://github.com/molenzwiebel/Deceive) is a program used to mask a player's online status while playing Riot games. It's decently popular and I use it myself, which is why I wrote this pull request.
I've added two new settings to the config: **use_deceive** and **install_location_deceive**.
In **tft.py**, I've changed **restart_league_client()** to take these configs into consideration and it now runs the new function **launch_league_client()**, which does most of the job.
If no path to deceive is given, the bot will run **determine_deceive_install_location()**. This function first searches the Downloads folder, then looks through a specific registry key I've found to contain paths of .exe files. 
Something to note is that these entries don't get deleted, meaning if a file …
> Added support for Deceive
